Repository bmstu-iu9/ptp2021-4-chat, pull requests merged in 2021-07, with the labels that each got.

#8 Создание обработчика для регистрации нового пользователя в системе и инициализация базовых сущностей
  .gitignore
  package-lock.json
  package.json
  server/config.js
  server/constants.js
  server/definitions.js
  server/http_handlers/index.js
  server/http_handlers/registration.js
  server/models/session.js
  server/models/user.js
  server/run.js
  server/services/registration.js
Labels: feature

#9 Рефакторинг кода: добавление отступов, переименование некоторых переменных
  server/config.js
  server/constants.js
  server/http_handlers/registration.js
  server/models/session.js
  server/models/user.js
  server/run.js
  server/services/registration.js
Labels: refactoring

#22 Рефактор кода и исправление незначительного бага
  server/config.js
  server/definitions.js
  server/http_handlers/authentication.js
  server/http_handlers/registration.js
  server/middleware.js
  server/middleware/index.js
  server/middleware/usernameAndPassword.js
  server/run.js
Labels: backend, fix, refactoring

#24 Дополнение инструкции по развертке проекта через докер
  README.md
Labels: documentation

#30 Добавление логгера для бэкенда
  server/logger.js
Labels: backend, feature

#33 Исправление ошибки, когда сессия жила силшком мало. Добавление ссылок…
  server/constants.js
Labels: backend, fix

#34 Переработка системы middleware, добавление новых
  server/middleware/index.js
  server/middleware/session.js
  server/middleware/staticUrl.js
  server/middleware/usernameAndPassword.js
Labels: backend, refactoring

#35 Переработка системы обработчиков
  package-lock.json
  server/definitions.js
  server/http_handlers/authentication.js
  server/http_handlers/registration.js
  server/models/user.js
  server/services/authentication.js
  server/services/common.js
  server/services/registration.js
  server/start.js
Labels: backend, refactoring

#38 Объявление объекта логера в definitions.js
  server/definitions.js
Labels: backend

#39 Добавление обработчика ошибок
  server/middleware/errorHandler.js
  server/middleware/index.js
Labels: backend, feature

#46 Изменение имени и значения переменной окружения
  docker-compose.prod.yml
  server/config.js
Labels: backend

#47 Изменение названия html-файла со страницей входа
  server/constants.js
  src/entry.html
Labels: backend, frontend

#52 Добавление медиа-запроса для изменения порядка контейнеров
  src/styles/login.css
Labels: frontend

#48 Изменение моделей базы данных
  server/models/index.js
  server/models/session.js
  server/models/user.js
  server/services/authentication.js
  server/services/common.js
  server/services/registration.js
Labels: backend

#49 Изменение способа настройки ORM при её инициализации
  server/start.js
Labels: backend

#50 Визуальный рефакторинг кода
  server/config.js
  server/constants.js
  server/definitions.js
  server/http_handlers/authentication.js
  server/http_handlers/registration.js
  server/logger.js
  server/middleware/index.js
  server/middleware/session.js
  server/middleware/staticUrl.js
  server/middleware/usernameAndPassword.js
Labels: backend, refactoring

#51 Добавление упоминания env-файла в readme
  README.md
Labels: documentation, environment

#57 Переименование css-файла для страницы входа/регистрации
  src/styles/entry.css
Labels: frontend

#58 Добавление формы регистрации
  src/entry.html
  src/js/entry.js
  src/styles/entry.css
Labels: frontend

#59 Добавление функции валидации логина и пароля
  src/js/entry.js
Labels: frontend

#56 Исправление недочетов связанных с названиями файлов
  src/index.html
  src/js/index.js
  src/styles/index.css
Labels: frontend

#61 Создание обработчика для выхода пользователя из системы
  server/http_handlers/index.js
  server/http_handlers/logout.js
  server/services/logout.js
Labels: backend, feature

#63 Переименование имени константы в объекте urls
  server/constants.js
  server/middleware/index.js
Labels: backend, refactoring

#64 Создание папки misc, перемещение туда логера и создание файла с утилитами
  server/misc/logger.js
  server/misc/utls.js
Labels: backend

#65 Изменение принципа работы обработчиков с применением функции-декоратора
  server/definitions.js
  server/http_handlers/authentication.js
  server/http_handlers/logout.js
  server/http_handlers/registration.js
  server/services/authentication.js
  server/services/registration.js
Labels: backend, fix

#66 Добавление передачи ошибки в обработчик ошибок в middleware
  server/middleware/session.js
Labels: backend, fix

#67 Рефакторинг html- и js-файлов страницы входа
  src/entry.html
  src/js/entry.js
Labels: frontend, refactoring

#73 Исправление поведения функции аутентификации
  server/services/authentication.js
  server/services/registration.js
Labels: backend, fix

#72 Добавление ключевого слова await
  server/http_handlers/registration.js
Labels: backend, fix

#74 Исправление регистрозависимости поиска пользователя по имени
  server/models/user.js
  server/services/authentication.js
  server/services/registration.js
Labels: backend, fix

#75 Добавление окна с уведомлением
  src/entry.html
  src/js/entry.js
  src/styles/entry.css
Labels: feature, frontend

#82 Изменение способа регистрации пользователя
  server/http_handlers/registration.js
  server/services/authentication.js
  server/services/common.js
  server/services/registration.js
Labels: backend

#83 Функция проверки имени на валидность
  src/js/validation.js
Labels: frontend

#81 Очистка полей ввода
  src/entry.html
  src/js/entry.js
Labels: frontend

#84 Добавление функций для получения и установки URL-параметров
  src/js/entry.js
Labels: feature, frontend

#85 Изменение способа валидации пароля
  src/js/entry.js
Labels: frontend

#89 Рефакторинг выбрасываемых исключений
  common/common.js
  server/http_handlers/authentication.js
  server/http_handlers/logout.js
  server/http_handlers/registration.js
  server/middleware/usernameAndPassword.js
  server/misc/utils.js
  server/services/authentication.js
  server/services/registration.js
Labels: backend

#91 Модификация декоратора wrapAsyncHandler
  common/common.js
  server/constants.js
  server/http_handlers/authentication.js
  server/http_handlers/logout.js
  server/http_handlers/registration.js
  server/middleware/errorHandler.js
  server/middleware/index.js
  server/middleware/session.js
  server/middleware/usernameAndPassword.js
  server/misc/utils.js
  server/services/authentication.js
  server/services/common.js
  server/services/registration.js
Labels: backend

#90 Изменение порядка импорта скриптов
  src/entry.html
Labels: fix, frontend

#92 Подключение страницы входа и регистрации к серверу
  src/entry.html
  src/js/entry.js
  src/styles/entry.css
Labels: frontend

#93 Исправление ошибки, когда окно уведомления могло иметь не тот цвет
  src/js/entry.js
Labels: fix, frontend

#94 Изменение способа вставки url-параметров
  src/js/entry.js
Labels: fix, frontend
