Repository bmstu-iu9/ptp2021-4-chat, pull requests merged in 2021-08, with the labels that each got.

#99 Добавление моделей для системы диалогов/бесед
  server/models/content.js
  server/models/conversation.js
  server/models/index.js
  server/models/message.js
  server/models/user.js
Labels: feature, backend

#101 Рефакторинг
  server/definitions.js
  server/http/handlers/authentication.js
  server/http/handlers/index.js
  server/http/handlers/logout.js
  server/http/handlers/registration.js
  server/http/index.js
  server/http/middleware/body.js
  server/http/middleware/errors.js
  server/http/middleware/index.js
  server/http/middleware/session.js
  server/http/middleware/static.js
  server/http/services/authentication.js
  server/http/services/common.js
  server/http/services/logout.js
  server/http/services/registration.js
  server/middleware/usernameAndPassword.js
  server/misc/HTTPError.js
  server/misc/WSServer.js
  server/misc/utils.js
  server/start.js
  src/js/entry.js
Labels: refactoring, backend, frontend

#102 Переработка файловой структуры и способов запуска проекта
  Dockerfile
  README.md
  docker-compose.prod.yml
  docker-compose.yml
  package-lock.json
  package.json
  server/config.js
  server/database/migrate.js
  server/database/models/content.js
  server/database/models/conversation.js
  server/database/models/index.js
  server/database/models/message.js
  server/database/models/session.js
  server/database/models/user.js
  server/database/sequelize.js
  server/database/sequelizePostgresFix.js
  server/definitions.js
  server/http/services/authentication.js
  server/http/services/common.js
  server/http/services/logout.js
  server/http/services/registration.js
  server/misc/HTTPError.js
  server/misc/utils.js
  server/start.js
Labels: refactoring, backend

#103 Добавление WS-обработчиков
  package-lock.json
  package.json
  server/http/services/common.js
  server/start.js
  server/ws/handlers/close.js
  server/ws/handlers/connection.js
  server/ws/handlers/error.js
  server/ws/handlers/index.js
  server/ws/handlers/message/endpoints/createMessage.js
  server/ws/handlers/message/endpoints/deleteMessage.js
  server/ws/handlers/message/endpoints/editMessage.js
  server/ws/handlers/message/endpoints/getAllConversations.js
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/handlers/message/endpoints/index.js
  server/ws/handlers/message/endpoints/readMessage.js
  server/ws/handlers/message/index.js
  server/ws/handlers/message/modifier.js
  server/ws/handlers/message/router.js
  server/ws/index.js
Labels: feature, backend

#106 Добавление обработчика getUser
  server/ws/handlers/message/endpoints/getUser.js
  server/ws/handlers/message/endpoints/index.js
  server/ws/services/user.js
Labels: feature, backend

#105 Добавление колонки relativeId в модель Message
  server/database/models/message.js
Labels: backend

#104 Переработка WS-ошибок
  server/misc/WSError.js
  server/ws/handlers/connection.js
  server/ws/handlers/error.js
  server/ws/handlers/message/modifier.js
Labels: refactoring, backend

#107 Испрвление ошибок, нарушавших работу WS-обработчиков
  server/ws/handlers/error.js
  server/ws/handlers/message/endpoints/getUser.js
  server/ws/handlers/message/modifier.js
  server/ws/handlers/message/router.js
Labels: backend, fix

#108 Добавление в логер возможности логирования в консоль
  server/definitions.js
  server/misc/logger.js
Labels: feature, backend

#109 Добавление нового endpoint'а getConversation
  server/constants.js
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/services/conversation.js
  server/ws/services/messages.js
Labels: feature, backend

#111 Добавление WS-обработчика запроса getAllConversations
  server/ws/handlers/message/endpoints/getAllConversations.js
Labels: feature, backend

#110 Изменение функции получения данных для WS-обработчика
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/services/conversation.js
Labels: backend

#112 Добавление новых WS-обработчиков
  package-lock.json
  server/misc/WSServer.js
  server/misc/utils.js
  server/ws/handlers/connection.js
  server/ws/handlers/message/endpoints/createMessage.js
  server/ws/handlers/message/endpoints/editMessage.js
  server/ws/handlers/message/endpoints/getAllConversations.js
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/handlers/message/endpoints/getUser.js
  server/ws/services/conversation.js
  server/ws/services/messages.js
  server/ws/services/user.js
Labels: feature, backend

#113 Изменение схемы WS
  server/ws/handlers/message/router.js
  server/ws/services/conversation.js
Labels: backend

#114 Добавление в gulp возможности сборки js-файлов
  gulpfile.js
  package-lock.json
  package.json
Labels: feature, frontend, environment

#117 Исправление критического бага в обертке WSServer
  server/definitions.js
  server/misc/WSServer.js
  server/ws/handlers/message/endpoints/createMessage.js
  server/ws/handlers/message/endpoints/editMessage.js
  server/ws/handlers/message/endpoints/getAllConversations.js
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/handlers/message/endpoints/getUser.js
  server/ws/handlers/message/modifier.js
  server/ws/handlers/preConnection.js
Labels: backend, fix

#120 Изменение работы WSServer, добавление обработчиков
  server/database/models/discussion.js
  server/database/models/message.js
  server/definitions.js
  server/misc/WSError.js
  server/misc/WSServer.js
  server/misc/objectProcessor.js
  server/misc/utils.js
  server/ws/handlers/connection.js
  server/ws/handlers/index.js
  server/ws/handlers/message/endpoints/createMessage.js
  server/ws/handlers/message/endpoints/deleteMessage.js
  server/ws/handlers/message/endpoints/editMessage.js
  server/ws/handlers/message/endpoints/getAllConversations.js
  server/ws/handlers/message/endpoints/getConversation.js
  server/ws/handlers/message/endpoints/getUser.js
  server/ws/handlers/message/endpoints/index.js
  server/ws/handlers/message/endpoints/readMessage.js
  server/ws/handlers/message/modifier.js
  server/ws/handlers/message/router.js
  server/ws/handlers/preConnection.js
  server/ws/services/common.js
  server/ws/services/conversation.js
  server/ws/services/conversations/configs.js
  server/ws/services/conversations/index.js
  server/ws/services/messages.js
  server/ws/services/messages/configs.js
  server/ws/services/messages/index.js
  server/ws/services/user.js
  server/ws/services/users/configs.js
  server/ws/services/users/index.js
Labels: feature, refactoring, backend

#125 Подключение WS-обработчиков
  gulpfile.js
  server/ws/handlers/message/endpoints/createDialog.js
  server/ws/handlers/message/endpoints/createDiscussion.js
  server/ws/handlers/message/endpoints/index.js
  server/ws/services/common.js
  server/ws/services/conversations/index.js
  server/ws/services/users/index.js
Labels: backend

#126 Исправление настроек модели
  server/database/models/discussion.js
  server/database/models/index.js
Labels: backend

#139 Исправления кривого мерджа
  src/index.html
  src/js/modules/renderers/SidePanelRenderer.js
  src/styles/index.css
Labels: frontend, fix
